config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get    '/login'   => 'devise/sessions#new',     as: :new_session
    post   '/login'   => 'devise/sessions#create',  as: :user_session
    get '/sign_up' => 'users/registrations#new', as: :new_user_session
  end
  resources :test_modules
  resources :activities
  resources :products
  root 'products#index'

  get 'profile' => 'profile#show'
  get 'profile/:id' => 'profile#show', as: 'profile_show'
  post 'profile/follow' => 'profile#follow', as: 'profile_follow'
  post 'profile/unfollow' => 'profile#unfollow', as: 'profile_unfollow'
  get 'profile/:id/followers' => 'profile#followers', as: 'profile_followers'
  get 'profile/:id/following' => 'profile#following', as: 'profile_following'
  get 'profile/:id/shared' => 'profile#sharedProducts', as: 'profile_shared_products'
  get 'list/:id' => 'profile#showList', as: 'profile_list'
  get 'settings' => 'profile#settings', as: 'profile_settings'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "api/:user_email/:user_token/profile/:id" => 'profile#show',
      as: 'api_show_profile', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signin" => "profile#getAuthenticationToken",
      as: 'api_signin', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signup" => "profile#api_signup",
    as: 'api_signup', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }
 
 get "mrkt/:user_email/:user_token/getMutualFriendsImages/:friends" => 'profile#getMutualFriendsImages',
   as: 'mrkt_get_friends', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPostDetail/:post_id" => 'posts#getPostDetail',
   as: 'mrkt_get_detail', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getYardPosts" => 'posts#getYardPosts',
   as: 'mrkt_get_yardsposts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPosts" => 'posts#getPosts',
   as: 'mrkt_get_posts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/createPost" => "posts#createPost",
    as: 'mrkt_create_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ } 

post "mrkt/sendMessage" => "chats#sendMessage",
    as: 'mrkt_send_message', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getChats" => 'chats#getChats',
   as: 'mrkt_get_chats', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/setLocation" => "profile#setLocation",
    as: 'mrkt_set_location_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ , :latitude =>/[\w+\.-]+/,  :longitude => /[\w+\.-]+/}

 get "mrkt/:user_email/:user_token/setLocation/:latitude/:longitude" => 'profile#setLocation',
   as: 'mrkt_set_location', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/likePost" => "posts#likePost",
    as: 'mrkt_like_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

post "mrkt/dislikePost" => "posts#dislikePost",
    as: 'mrkt_dislike_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

  

end

app/models/test_module.rb
class TestModule < ActiveRecord::Base
end

app/controllers/test_modules_controller.rb
class TestModulesController < ApplicationController
  before_action :set_test_module, only: [:show, :edit, :update, :destroy]

  # GET /test_modules
  # GET /test_modules.json
  def caphov
  end

  def flat
  end
  
  def colorz
  end

  def escape
  end
  
  def index
    @test_modules = TestModule.all
  end

  # GET /test_modules/1
  # GET /test_modules/1.json
  def show
  end

  # GET /test_modules/new
  def new
    @test_module = TestModule.new
  end

  # GET /test_modules/1/edit
  def edit
  end

  # POST /test_modules
  # POST /test_modules.json
  def create
    @test_module = TestModule.new(test_module_params)

    respond_to do |format|
      if @test_module.save
        format.html { redirect_to @test_module, notice: 'Test module was successfully created.' }
        format.json { render :show, status: :created, location: @test_module }
      else
        format.html { render :new }
        format.json { render json: @test_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_modules/1
  # PATCH/PUT /test_modules/1.json
  def update
    respond_to do |format|
      if @test_module.update(test_module_params)
        format.html { redirect_to @test_module, notice: 'Test module was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_module }
      else
        format.html { render :edit }
        format.json { render json: @test_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_modules/1
  # DELETE /test_modules/1.json
  def destroy
    @test_module.destroy
    respond_to do |format|
      format.html { redirect_to test_modules_url, notice: 'Test module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_module
      @test_module = TestModule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_module_params
      params[:test_module]
    end
end

app/helpers/test_modules_helper.rb
module TestModulesHelper
end

app/views/test_modules/_form.html.erb
<%= form_for(@test_module) do |f| %>
  <% if @test_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_module.errors.count, "error") %> prohibited this test_module from being saved:</h2>

      <ul>
      <% @test_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_modules/caphov.html.erb
		<div class="container demo-7">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				<a class="codrops-icon codrops-icon-prev" href="http://tympanus.net/Development/CreativeButtons/"><span>Previous Demo</span></a>
				<span class="right"><a class="codrops-icon codrops-icon-drop" href="http://tympanus.net/codrops/?p=15469"><span>Back to the Codrops Article</span></a></span>
			</div>
			<header>
				<h1>Caption Hover Effects</h1>	
				<nav class="codrops-demos">
					<a href="index.html">Effect 1</a>
					<a href="index2.html">Effect 2</a>
					<a href="index3.html">Effect 3</a>
					<a href="index4.html">Effect 4</a>
					<a href="index5.html">Effect 5</a>
					<a href="index6.html">Effect 6</a>
					<a class="current-demo" href="index7.html">Effect 7</a>
				</nav>
			</header>
			<ul class="grid cs-style-7">
				<li>
					<figure>
						<img src="/assets/6.png" alt="img06">
						<figcaption>
							<h3>Game Center</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1118904-Game-Center">Take a look</a>
						</figcaption>
					</figure>
				</li>
				<li>
					<figure>
						<img src="//assets/4.png" alt="img04">
						<figcaption>
							<h3>Settings</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1116685-Settings">Take a look</a>
						</figcaption>
					</figure>
				</li>
				<li>
					<figure>
						<img src="/assets/2.png" alt="img02">
						<figcaption>
							<h3>Music</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
				<li>
					<figure>
						<img src="/assets/5.png" alt="img05">
						<figcaption>
							<h3>Safari</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1116775-Safari">Take a look</a>
						</figcaption>
					</figure>
				</li>
				<li>
					<figure>
						<img src="/assets/1.png" alt="img01">
						<figcaption>
							<h3>Camera</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115632-Camera">Take a look</a>
						</figcaption>
					</figure>
				</li>
				<li>
					<figure>
						<img src="/assets/3.png" alt="img03">
						<figcaption>
							<h3>Phone</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1117308-Phone">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
		</div><!-- /container -->	
<ul class="grid cs-style-7">
				<li class="">
							<figure>
						<img class="center-cropped" src="/assets/6.png" alt="img06">
						<figcaption>
							<h3>Game Center</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1118904-Game-Center">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>

app/views/test_modules/colorz.html.erb
<div class="portfolio logo1 mix_all" data-cat="logo" style="display: inline-block; opacity: 1;">
								<div class="portfolio-wrapper">
									<a href="#"> <img src="images/s1.jpg" alt="Image 1" style="top: 0px;"> </a>
									<div class="label_style">
										<a href="#"><span class="icon_1"></span></a>
										<div class="label_text">
											<h2>scarabaeidae</h2>
											<p>Rezonum &amp; Collections</p>
										</div>
									</div>
								</div>
							</div>
<div class="wrap">
	<div class="span_of_2"><!-- start span_of_2 -->
		<div class="span1_of_1"><!-- start span1_of_1 -->
			<div class="container"><!-- start container -->
						<ul id="filters" class="clearfix">
							<li><span class="filter active" data-filter="app card icon web">All</span></li>
							<li><span class="filter" data-filter="logo  web">Photography</span></li>
							<li><span class="filter" data-filter="app card icon web">Inspirations</span></li>
							<li><span class="filter" data-filter="logo  web">Icon</span></li>
						</ul>
						<div id="portfoliolist">
							<div class="portfolio logo1" data-cat="logo">
								<div class="portfolio-wrapper">
									<a href="#"> <img src="images/s1.jpg"  alt="Image 1" /> </a>
									<div class="label_style">
										<a href="#"><span class="icon_1"></span></a>
										<div class="label_text">
											<h2>scarabaeidae</h2>
											<p>Rezonum & Collections</p>
										</div>
									</div>
								</div>
							</div>
							<div class="portfolio app left" data-cat="app">
								<div class="portfolio-wrapper">
									<a href="#"> <img src="images/s2.jpg"  alt="Image 2" /> </a>
									<div class="label_style">
										<a href="#"><span class="icon_2"></span></a>
										<div class="label_text">
											<h2>scarabaeidae</h2>
											<p>Rezonum & Collections</p>
										</div>
									</div>
								</div>
							</div>
							<div class="portfolio web" data-cat="web">
								<div class="portfolio-wrapper">
									<a href="#"> <img src="images/s3.jpg"  alt="Image 3" /> </a>
									<div class="label_style">
										<a href="#"><span class="icon_3"></span></a>
										<div class="label_text">
											<h2>scarabaeidae</h2>
											<p>Rezonum & Collections</p>
											<form>
												<input type="button" value="buy it now" />
											</form>
										</div>
									</div>
								</div>
							</div>
							<div class="portfolio card left" data-cat="card">
								<div class="portfolio-wrapper">
									<a href="#"> <img src="images/s4.jpg"  alt="Image 4" /> </a>
									<div class="label_style">
										<a href="#"><span class="icon_4"></span></a>
										<div class="label_text">
											<h2>scarabaeidae</h2>
											<p>Rezonum & Collections</p>
											<form>
												<input type="button" class="bg" value="buy it now" />
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
			</div><!-- end container -->
			<div class="span_btm">
				<img src="images/pic1.jpg" alt=""/>
				<div class="span_text">
					<h3>ios games / slots</h3>
					<p>Written by <a href="#">eiusmod tempor incididunt</a> </p>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
					<p>Contrary to popular belief, Lorem Ipsum is not simply random text.</p>
					<form>
						<span><input type="button" class="bg" value="like it now" /> </span>
						<span><input type="button" class="bg1" value="learn more" /> </span>
						<div class="clear"></div>
						<span class="or">or</span>
					</form>
				</div>
			</div>
		</div><!-- end span1_of_1 -->
		<div class="span1_of_2"><!-- start span1_of_2 -->
			<div class="slider"><!-- start slider -->
				<div id="da-slider" class="da-slider">
						<div class="da-slide">
							<h2>Flat Design websites</h2>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
						</div>
						<div class="da-slide">
							<h2>Clean & Flat Design</h2>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
						</div>
						<div class="da-slide">
							<h2>Clean & Flat Design</h2>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
						</div>
						<div class="da-slide">
							<h2>Flat Design websites</h2>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
						</div>
						<nav class="da-arrows">
							<span class="da-arrows-prev"></span>
							<span class="da-arrows-next"></span>
						</nav>
				</div>
			</div><!-- end slider -->
			<div class="grids_of_2">
				<div class="grid1_of_1">
					<div class="temparature">
						<h4 class="left">4<sup>o</sup>c</h4>
						<span class="right bg"></span>
						<div class="clear"></div>
					</div>
					<div class="temp_list_main">
						<div class="temp_main">
							<ul class="temp_list">
								<li><span class="temp_img"><img src="images/temp1.jpg" alt=""/></span><span class="temp_text"><h4>Mon</h4><h5>30<sup>o</sup></h5></span><div class="clear"></div></li>
							</ul>
							<ul class="temp_list_icon">
								<li><i class="icon_1"></i></li>
							</ul>
							<div class="clear"></div>
						</div>
						<div class="temp_main top">
							<ul class="temp_list">
								<li><span class="temp_img"><img src="images/temp2.jpg" alt=""/></span><span class="temp_text"><h4>Thu</h4><h5>27<sup>o</sup></h5></span><div class="clear"></div></li>
							</ul>
							<ul class="temp_list_icon">
								<li><i class="icon_2"></i></li>
							</ul>
							<div class="clear"></div>
						</div>
					</div>
				</div>
				<div class="grid1_of_2">
					<form>
						<input type="button" value="button one" class="bg1" />
						<input type="button" value="button two" class="bg2" />
						<input type="button" value="button three" class="bg3" />
						<div class="clear"></div>
					</form>
					<ul class="list">
						<li><a href="#">summer</a> </li>
						<li><a href="#">hot</a> </li>
						<li><a href="#">party</a> </li>
						<li><a href="#">musical</a> </li>
					</ul>
					<ul class="soc_icons">
						<li><a href="#" class="bg1">facebook <i class="icon_1"></i></a></li>
						<li><a href="#" class="bg2">twitter <i class="icon_2"></i></a></li>
						<li><a href="#" class="bg3">dribbble <i class="icon_3"></i></a></li>
					</ul>
					<div class="span_list">
						<div class="span_list_img">
							<img src="images/user1.jpg" alt=""/>
						</div>
						<div class="span_list_text">
							<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
							<fieldset class="star-rating" data-evaluated="wdw_3" data-stars="5" data-value="2" >
							</fieldset>			
							        <script src="js/jquery.starRating.js"></script>				
						</div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="grids_of_2 top">
				<div class="grid1_of_1">
					<div class="feeds">
						<h4>twiiter feeds</h4>
						<span class="refresh_b"><a class="refresh" href="#"></a></span>
						<div class="feeds_list">
							<div class="feeds_main">
								<div class="feeds_img">
									<img src="images/user2.jpg" alt="" />
								</div>
								<div class="feeds_text">
									<span><a href="#">Theme</a> is following you.</span>
								</div>
								<div class="clear"></div>
							</div>
							<div class="feeds_main">
								<div class="feeds_img">
									<img src="images/user3.jpg" alt="" />
								</div>
								<div class="feeds_text">
									<span><a href="#">There are many</a> Lorem Ipsum is simply dummy text of the printing.</span>
								</div>
								<div class="clear"></div>
							</div>
							<div class="feeds_main">
								<div class="feeds_img">
									<img src="images/user4.jpg" alt="" />
								</div>
								<div class="feeds_text">
									<span><a href="#">There are many lipsum</a> is following you.</span>
								</div>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="grid1_of_2">
					<div class="clouds_storage">
						<h4 class="left">clouds storage</h4>
						<span class="right bg"></span>
						<div class="clear"></div>
					</div>
						<ul class="cloud_list">
							<li><a href="#"><i class="icon_1"></i><span>unlimited space</span></a> </li>
							<li><a href="#"><i class="icon_1"></i><span> 1 month history </span></a> </li>
							<li class="active"><a href="#"><i class="icon_1"></i><span> 500 gb of space </span></a> </li>
							<li><a href="#"><i class="icon_1"></i><span> premium sources </span></a> </li>
							<li><a href="#"><span class="right">free 30 days trail</span></a></li>
							<div class="clear"></div>
						</ul>
				</div>
				<div class="clear"></div>
			</div>
			<div class="main_alert"><!-- alert style-1 -->
				<div class="grid_8">
					<div class="message alert style-1 rounded">
						<span><i class="icon_1"></i>Lorem Ipsum is simply<p class="hide"> dummy text of the printing</p></span><a href="#" class="close fade">x</a>
					</div>
				</div>
				<div class="grid_8">
					<div class="success alert style-1 rounded">
						<span><i class="icon_2"></i>There are many <p class="hide">variations of passages of Lorem ipsum</p></span><a href="#" class="close slide">x</a>
					</div>
				</div>
				<div class="grid_8">
					<div class="error alert style-1 rounded">
						<span><i class="icon_3"></i>The standard chunk <p class="hide">of Lorem Ipsum</p></span><a href="#" class="close fade-slide">x</a>
					</div>
  				</div>
			</div>			
		</div><!-- end span1_of_2 -->
		<div class="clear"></div>
		<div class="copy"><!-- start copy -->
			<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
		</div>
	</div><!-- end span_of_2 -->
</div>

app/views/test_modules/edit.html.erb
<h1>Editing test_module</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_module %> |
<%= link_to 'Back', test_modules_path %>

app/views/test_modules/index.html.erb
<h1>Listing test_modules</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_modules.each do |test_module| %>
      <tr>
        <td><%= link_to 'Show', test_module %></td>
        <td><%= link_to 'Edit', edit_test_module_path(test_module) %></td>
        <td><%= link_to 'Destroy', test_module, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test module', new_test_module_path %>

app/views/test_modules/new.html.erb
<h1>New test_module</h1>

<%= render 'form' %>

<%= link_to 'Back', test_modules_path %>

app/views/test_modules/old.test.html.erb

		<!-- Banner -->		
			<section id="banner">
				
				<!--
					".inner" is set up as an inline-block so it automatically expands
					in both directions to fit whatever's inside it. This means it won't
					automatically wrap lines, so be sure to use line breaks where
					appropriate (<br />).
				-->
				<div class="inner">
					
					<header>
						<h2>TWENTY</h2>
					</header>
					<p>This is <strong>Twenty</strong>, a free<br />
					responsive template<br />
					by <a href="http://html5up.net">HTML5 UP</a>.</p>
					<footer>
						<div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
						<% if session[:user_id] %>
						<ul class="buttons vertical">
							<li><a href="#main" class="button fit scrolly">Hello again!</a></li>
						</ul>
						<% else %>
						<ul class="buttons vertical">
							<li><a href="#main" class="button fit scrolly">Sign Up With Facebook</a></li>
						</ul>
						<% end %>
					</footer>
				
				</div>
				
			</section>
		
		<!-- Main -->
			<article id="main">

				<header class="special container">
					<span class="icon fa-bar-chart-o"></span>
					<h2>As this is my <strong>twentieth</strong> freebie for HTML5 UP<br />
					I decided to give it a really creative name.</h2>
					<p>Turns out <strong>Twenty</strong> was the best I could come up with. Anyway, lame name aside,<br />
					it's minimally designed, fully responsive, built on HTML5/CSS3/<strong>skel</strong>, 
					and, like all my stuff,<br />
					released for free under the <a href="http://html5up.net/license">Creative Commons Attribution 3.0</a> license. Have fun!</p>
				</header>
					
				<!-- One -->
					<section class="wrapper style2 container special-alt">
						<div class="row half">
							<div class="8u">
							
								<header>
									<h2>Behold the <strong>icons</strong> that visualize what you’re all about. or just take up space. your call bro.</h2>
								</header>
								<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu comteger ut fermentum lorem. Lorem ipsum dolor sit amet. Sed tristique purus vitae volutpat ultrices. eu elit eget commodo. Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo.</p>
								<footer>
									<ul class="buttons">
										<li><a href="#" class="button">Find Out More</a></li>
									</ul>
								</footer>
							
							</div>
							<div class="4u skel-cell-important">
							
								<ul class="feature-icons">
									<li><span class="icon fa-clock-o"><span class="label">Feature 1</span></span></li>
									<li><span class="icon fa-volume-up"><span class="label">Feature 2</span></span></li>
									<li><span class="icon fa-laptop"><span class="label">Feature 3</span></span></li>
									<li><span class="icon fa-inbox"><span class="label">Feature 4</span></span></li>
									<li><span class="icon fa-lock"><span class="label">Feature 5</span></span></li>
									<li><span class="icon fa-cog"><span class="label">Feature 6</span></span></li>
								</ul>
							
							</div>				
						</div>
					</section>
					
				<!-- Two -->
					<section class="wrapper style1 container special">
						<div class="row">
							<div class="4u">
							
								<section>
									<span class="icon feature fa-check"></span>
									<header>
										<h3>This is Something</h3>
									</header>
									<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo suscipit dolor nec nibh. Proin a ullamcorper elit, et sagittis turpis. Integer ut fermentum.</p>
								</section>
							
							</div>
							<div class="4u">
							
								<section>
									<span class="icon feature fa-check"></span>
									<header>
										<h3>Also Something</h3>
									</header>
									<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo suscipit dolor nec nibh. Proin a ullamcorper elit, et sagittis turpis. Integer ut fermentum.</p>
								</section>
							
							</div>
							<div class="4u">
							
								<section>
									<span class="icon feature fa-check"></span>
									<header>
										<h3>Probably Something</h3>
									</header>
									<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo suscipit dolor nec nibh. Proin a ullamcorper elit, et sagittis turpis. Integer ut fermentum.</p>
								</section>
							
							</div>
						</div>
					</section>
					
				<!-- Three -->
					<section class="wrapper style3 container special">
					
						<header class="major">
							<h2>Next look at this <strong>cool stuff</strong></h2>
						</header>
						
						<div class="row">
							<div class="6u">
							
								<section>
									<a href="#" class="image feature"><img src="images/pic01.jpg" alt="" /></a>
									<header>
										<h3>A Really Fast Train</h3>
									</header>
									<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper sed blandit lorem ipsum dolore.</p>
								</section>

							</div>
							<div class="6u">
							
								<section>
									<a href="#" class="image feature"><img src="images/pic02.jpg" alt="" /></a>
									<header>
										<h3>An Airport Terminal</h3>
									</header>
									<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper sed blandit lorem ipsum dolore.</p>
								</section>

							</div>
						</div>
						<div class="row">
							<div class="6u">
							
								<section>
									<a href="#" class="image feature"><img src="images/pic03.jpg" alt="" /></a>
									<header>
										<h3>Hyperspace Travel</h3>
									</header>
									<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper sed blandit lorem ipsum dolore.</p>
								</section>

							</div>
							<div class="6u">
							
								<section>
									<a href="#" class="image feature"><img src="images/pic04.jpg" alt="" /></a>
									<header>
										<h3>And Another Train</h3>
									</header>
									<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper sed blandit lorem ipsum dolore.</p>
								</section>

							</div>
						</div>

						<footer class="major">
							<ul class="buttons">
								<li><a href="#" class="button">See More</a></li>
							</ul>
						</footer>
					
					</section>
					
			</article>

		<!-- CTA -->
			<section id="cta">
			
				<header>
					<h2>Ready to do <strong>something</strong>?</h2>
					<p>Proin a ullamcorper elit, et sagittis turpis integer ut fermentum.</p>
				</header>
				<footer>
					<ul class="buttons">
						<li><a href="#" class="button special">Take My Money</a></li>
						<li><a href="#" class="button">LOL Wut</a></li>
					</ul>
				</footer>
			
			</section>

		<!-- Footer -->
			<footer id="footer">
			
				<ul class="icons">
					<li><a href="#" class="icon circle fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon circle fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon circle fa-google-plus"><span class="label">Google+</span></a></li>
					<li><a href="#" class="icon circle fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon circle fa-dribbble"><span class="label">Dribbble</span></a></li>
				</ul>
				
				<span class="copyright">&copy; Untitled. All rights reserved. Design: <a href="http://html5up.net">HTML5 UP</a>.</span>
			
			</footer>

app/views/test_modules/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_test_module_path(@test_module) %> |
<%= link_to 'Back', test_modules_path %>