config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get    '/login'   => 'devise/sessions#new',     as: :new_session
    post   '/login'   => 'devise/sessions#create',  as: :user_session
    get '/sign_up' => 'users/registrations#new', as: :new_user_session
  end
  resources :test_modules
  resources :activities
  resources :products
  root 'products#index'

  get 'profile' => 'profile#show'
  get 'profile/:id' => 'profile#show', as: 'profile_show'
  post 'profile/follow' => 'profile#follow', as: 'profile_follow'
  post 'profile/unfollow' => 'profile#unfollow', as: 'profile_unfollow'
  get 'profile/:id/followers' => 'profile#followers', as: 'profile_followers'
  get 'profile/:id/following' => 'profile#following', as: 'profile_following'
  get 'profile/:id/shared' => 'profile#sharedProducts', as: 'profile_shared_products'
  get 'list/:id' => 'profile#showList', as: 'profile_list'
  get 'settings' => 'profile#settings', as: 'profile_settings'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "api/:user_email/:user_token/profile/:id" => 'profile#show',
      as: 'api_show_profile', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signin" => "profile#getAuthenticationToken",
      as: 'api_signin', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signup" => "profile#api_signup",
    as: 'api_signup', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }
 
 get "mrkt/:user_email/:user_token/getMutualFriendsImages/:friends" => 'profile#getMutualFriendsImages',
   as: 'mrkt_get_friends', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPostDetail/:post_id" => 'posts#getPostDetail',
   as: 'mrkt_get_detail', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getYardPosts" => 'posts#getYardPosts',
   as: 'mrkt_get_yardsposts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPosts" => 'posts#getPosts',
   as: 'mrkt_get_posts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/createPost" => "posts#createPost",
    as: 'mrkt_create_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ } 

post "mrkt/sendMessage" => "chats#sendMessage",
    as: 'mrkt_send_message', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getChats" => 'chats#getChats',
   as: 'mrkt_get_chats', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/setLocation" => "profile#setLocation",
    as: 'mrkt_set_location_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ , :latitude =>/[\w+\.-]+/,  :longitude => /[\w+\.-]+/}

 get "mrkt/:user_email/:user_token/setLocation/:latitude/:longitude" => 'profile#setLocation',
   as: 'mrkt_set_location', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/likePost" => "posts#likePost",
    as: 'mrkt_like_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

post "mrkt/dislikePost" => "posts#dislikePost",
    as: 'mrkt_dislike_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

  

end

app/views/shared/_filters.html.erb
<ul class="list">
	<li class="vigme-filters"><%= link_to 'All', '/products?all=1' %></a> </li>
	<% @categories.each do |category| %>
	<li class="vigme-filters"><%= link_to category.name, '/products?' + category.name.delete(' ') + '=1' %></a> </li>
		
	<% end %>
</ul>

app/views/shared/_filters_profile.html.erb
<ul class="list">
	<li class="vigme-filters"><%= link_to 'All', '?all=1' %></a> </li>
	<% @categories.each do |category| %>
	<li class="vigme-filters"><%= link_to category.name, '?' + category.name.delete(' ') + '=1' %></a> </li>
		
	<% end %>
</ul>

app/views/shared/_list_modal.html.erb

<div class="modal" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vigme-list-modal-dialog modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="vigme-center-text modal-title" id="myModalLabel">Save to a list?</h4>
      </div>

      <% if user_signed_in? %>

      <div id="<%= modal_id %>_body" class="modal-body">

      </div>

      <% else %>

      <div class="vigme-button-div col-md-offset-2">
        <a href="/auth/facebook">
        <button type="button" class="vigme-button btn btn-primary">Sign Up to Share your Style!</button>
        </a>
      </div>

      <% end %>


      <div class="modal-footer">
        <button id="close-list-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_post_product_modal.html.erb

<div class="modal fade" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Post a Product!</h4>
      </div>

      <% if user_signed_in? %>

      <div id="<%= modal_id %>_body" class="modal-body">
          <div class="col-md-offset-2">
            <%= render 'products/url_form' %>
          </div>
      </div>

      <% else %>

      <div class="vigme-button-div col-md-offset-2">
        <a href="/auth/facebook">
        <button type="button" class="vigme-button btn btn-primary">Sign Up to Share your Style!</button>
        </a>
      </div>

      <% end %>


      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_product_detail_modal.html.erb

<div class="modal" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div id="<%= modal_id %>_dialog" class="modal-dialog">
    <div class="vigme-modal-content modal-content">

      <div id="<%= modal_id %>_body" class="modal-body">

      </div>

      <div class="modal-footer">
        <button id="close-list-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
$(function() {
  return $('#product_detail_modal').on('scroll', function() {
    var delay;
    console.log($('#product_detail_modal').scrollTop());
    console.log($('#product_detail_modal_dialog').height() - 2500);
    if ($('#product_detail_modal').scrollTop() > $('#product_detail_modal_dialog').height() - 2500) {
      $("#more_products_modal").click();
      $("#more_products_modal").attr('disabled', true);
      console.log("test");
      delay = function(ms, func) {
        return setTimeout(func, ms);
      };
      delay(1000, function() {
        return $("#more_products_modal").removeAttr('disabled');
      });
      console.log("testafter");
    }
  });
});

</script>

app/views/shared/_product_list.html.erb

<% products.each do |product| %>
	<div class="vigme-product-outline"> 
		<div class="vigme-product-overlay-main vigme-product-overlay">
			<%= truncate(product["name"], :length => 60) || truncate(product.name, :length => 60) %>
			<div class="vigme-button-overlay-main">
				<%= button_to 'Save', {controller: 'products', action: 'share', :product => product["id"] || product.id}, :method => :post, :class => 'vigme-save-button-overlay btn btn-primary', :remote => true, 'data-toggle' => 'modal', 'data-target' => '#list_modal' %>
			<div class="vigme-price-overlay">
				<span class="vigme-overlay-price-text">$<%= product["price"] || product.price %></span>
			</div>
			</div>

		</div>
		<%= link_to image_tag( product["image"] || product.image_s3_url, :class=> "vigme-product-image"), {:controller => 'products', :action => "showProductModal", :id => (product["id"] || product.id) }, remote: :true, 'data-toggle' => 'modal', 'data-target' => '#product_detail_modal' %>
	</div> 


<% end %>

	

app/views/shared/_product_list_discover.html.erb

<div class="vigme-social-profile-row row"> 
		<%= image_tag profile.avatar.url, class: "vigme-social-profile-image" %>

	<a class="vigme-social-name"><%= profile.name %></a>

	<%= render 'profile/follow_button_small', user_info: profile, :unfollow => alreadyFollowed %>
</div>
<div class="vigme-social-product-group">
<% products.each do |product| %>
	<div class="vigme-product-outline-social"> 
		<%= link_to image_tag( product["image"] || product.image_s3_url, :class=> "vigme-product-social"), {:controller => 'products', :action => "showProductModal", :id => (product["id"] || product.id) }, remote: :true, 'data-toggle' => 'modal', 'data-target' => '#product_detail_modal' %>
	</div> 
  <% end %>
</div>

	

app/views/shared/_product_list_lists.html.erb

<div class="vigme-list-profile-row row"> 
	<a href="<%= profile_list_path(list.id) %>"><h3 class="vigme-header-3"><%= list.title %></h3></a>
</div>
<div class="vigme-list-product-group">

<%= render "shared/product_list_profile", products: products %>
</div>

	

app/views/shared/_product_list_mini.html.erb

<% products.each do |product| %>
	<div class="vigme-product-outline-mini"> 
		<%= link_to image_tag( product["image"] || product.image_s3_url, :class=> "vigme-products-mini"), {:controller => 'products', :action => "showProductModal", :id => (product["id"] || product.id) }, remote: :true, 'data-toggle' => 'modal', 'data-target' => '#product_detail_modal' %>
	</div> 
<% end %>

	

app/views/shared/_product_list_profile.html.erb
<% products.each do |product| %>
	<div class="vigme-product-outline-social"> 
		<%= link_to image_tag( product["image"] || product.image_s3_url, :class=> "vigme-product-social"), {:controller => 'products', :action => "showProductModal", :id => (product["id"] || product.id) }, remote: :true, 'data-toggle' => 'modal', 'data-target' => '#product_detail_modal' %>
	</div> 
<% end %>

app/views/shared/_product_list_social.html.erb

<div class="vigme-social-profile-row row"> 
		<%= image_tag profile.avatar.url, class: "vigme-social-profile-image" %>

	<a class="vigme-social-name"><%= profile.name %></a>
</div>
<div class="vigme-social-product-group">
<% products.each do |product| %>
	<div class="vigme-product-outline-social"> 
		<%= link_to image_tag( product["image"] || product.image_s3_url, :class=> "vigme-product-social"), {:controller => 'products', :action => "showProductModal", :id => (product["id"] || product.id) }, remote: :true, 'data-toggle' => 'modal', 'data-target' => '#product_detail_modal' %>
	</div> 
  <% end %>
</div>

	

app/views/shared/_share_modal.html.erb

<div class="modal" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Share Your Style!</h4>
      </div>

      <% if user_signed_in? %>

      <div id="<%= modal_id %>_body" class="modal-body">
        <div class="row">
          <div class="col-md-offset-2">
            <%= render 'shared/share_form' %>
          </div>
        </div>

      </div>

      <% else %>

      <div class="vigme-button-div col-md-offset-2">
        <a href="/auth/facebook">
        <button type="button" class="vigme-button btn btn-primary">Sign Up to Share your Style!</button>
        </a>
      </div>

      <% end %>


      <div class="modal-footer">
        <div class="row">
          <div class="col-md-offset-0">
            <h3 class="vigme-center-text vigme-header-3">Want to post products faster?</h3>

          </div>
        </div>

        <div class="row">
          <div class="col-md-offset-0 vigme-center-text">
            <h3 class="vigme-center-text vigme-header-3"> Drag this button to your browser's Bookmark bar!</h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-offset-0 vigme-center-text vigme-vigit-modal">
            <%= link_to '+Vig It', easymarklet_js('bookmarklet/fvb_bare_bookmarklet.js'), class: "vigme-bookmarklet" %>
          </div>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb

<div class="modal fade" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog vigme-signup-modal">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign up for Vigme!</h4>
      </div>

      <div id="<%= modal_id %>_body" class="modal-body">




      </div>


      <div class="vigme-center-text vigme-button-div col-md-offset-0">
        <%= link_to "Sign Up With Facebook", user_omniauth_authorize_path(:facebook), class: "vigme-button btn btn-primary" %>

      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_vigor.html.erb
	<div class="vigme-vigor row">
		<% if rank == "bronze" %>
			<div class="w-group">

				<a style="border-color: transparent transparent #C5A82F transparent;" id="w-triangle"></a>
				<a style="border-color: transparent transparent #C5A82F transparent;" id="w-triangle"></a>
			</div>
				<a style="border-color: #C5A82F transparent transparent transparent;" id="v-triangle"></a>
		<% else %>
			<div class="w-group">
				<a id="w-triangle"></a>
				<a id="w-triangle"></a>
			 </div>
			<a id="v-triangle"></a>
		<% end %>

	</div>