config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get    '/login'   => 'devise/sessions#new',     as: :new_session
    post   '/login'   => 'devise/sessions#create',  as: :user_session
    get '/sign_up' => 'users/registrations#new', as: :new_user_session
  end
  resources :test_modules
  resources :activities
  resources :products
  root 'products#index'

  get 'profile' => 'profile#show'
  get 'profile/:id' => 'profile#show', as: 'profile_show'
  post 'profile/follow' => 'profile#follow', as: 'profile_follow'
  post 'profile/unfollow' => 'profile#unfollow', as: 'profile_unfollow'
  get 'profile/:id/followers' => 'profile#followers', as: 'profile_followers'
  get 'profile/:id/following' => 'profile#following', as: 'profile_following'
  get 'profile/:id/shared' => 'profile#sharedProducts', as: 'profile_shared_products'
  get 'list/:id' => 'profile#showList', as: 'profile_list'
  get 'settings' => 'profile#settings', as: 'profile_settings'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "api/:user_email/:user_token/profile/:id" => 'profile#show',
      as: 'api_show_profile', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signin" => "profile#getAuthenticationToken",
      as: 'api_signin', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signup" => "profile#api_signup",
    as: 'api_signup', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }
 
 get "mrkt/:user_email/:user_token/getMutualFriendsImages/:friends" => 'profile#getMutualFriendsImages',
   as: 'mrkt_get_friends', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPostDetail/:post_id" => 'posts#getPostDetail',
   as: 'mrkt_get_detail', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getYardPosts" => 'posts#getYardPosts',
   as: 'mrkt_get_yardsposts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPosts" => 'posts#getPosts',
   as: 'mrkt_get_posts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/createPost" => "posts#createPost",
    as: 'mrkt_create_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ } 

post "mrkt/sendMessage" => "chats#sendMessage",
    as: 'mrkt_send_message', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getChats" => 'chats#getChats',
   as: 'mrkt_get_chats', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/setLocation" => "profile#setLocation",
    as: 'mrkt_set_location_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ , :latitude =>/[\w+\.-]+/,  :longitude => /[\w+\.-]+/}

 get "mrkt/:user_email/:user_token/setLocation/:latitude/:longitude" => 'profile#setLocation',
   as: 'mrkt_set_location', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/likePost" => "posts#likePost",
    as: 'mrkt_like_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

post "mrkt/dislikePost" => "posts#dislikePost",
    as: 'mrkt_dislike_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	validates :activity_type, presence: true
	# all activity_types
	validate :add_to_list_validator, :save_validator, :list_validator,
	 :add_validator, :follow_validator, :seen_validator

	belongs_to :user, :foreign_key => 'fromUser'
	belongs_to :product
	belongs_to :list

	has_attached_file :receipt
	validates_attachment_content_type :receipt, :content_type => ["text/html"]

	def add_to_list_validator
		if activity_type == "add_to_list"
			# checks for missing fields and missing product for this activity type
			if fromUser.nil? || product_id.nil? || list_id.nil? || product.nil?
				errors.add(:add_to_list, "missing fields!")
				return false
			end
		end
		return true
	end

	def save_validator
		if activity_type == "save"
			if fromUser.nil? || product_id.nil? || product.nil?
				errors.add(:save, "missing fields!")
				return false
			end
		end
	end

	def list_validator
		if activity_type == "list"
			if fromUser.nil? || list_id.nil?
				errors.add(:list, "missing fields!")
				return false
			end
		end
	end

	def add_validator
		if activity_type == "add"
			if fromUser.nil? || product_id.nil? || product.nil?
				errors.add(:add, "missing fields!")
				return false
			end
		end
	end

	def follow_validator
		if activity_type == "follow"
			if fromUser.nil? || toUser.nil?
				errors.add(:follow, "missing fields!")
				return false
			end
			from = User.where(:id => toUser).count
			if from == 0
				errors.add(:follow, "No id of user to follow")
				return false
			end
		end
	end

	def seen_validator
		if activity_type == "seen"
			if fromUser.nil? || product_id.nil? || product.nil?
				errors.add(:seen, "missing fields!")
				return false
			end
			activity = Activity.where(:activity_type => "seen", :product_id => product_id)
			.where(:fromUser => fromUser, :toUser => toUser).count
			if activity != 0
				errors.add(:seen, "user already saw this product")
				return false
			end
		end
	end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:fromUser, :toUser, :type, :product)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fromUser %><br>
    <%= f.text_field :fromUser %>
  </div>
  <div class="field">
    <%= f.label :toUser %><br>
    <%= f.text_field :toUser %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Fromuser</th>
      <th>Touser</th>
      <th>Type</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<%= current_user.name %>
 <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.fromUser %></td>
        <td><%= activity.toUser %></td>
        <td><%= activity.type %></td>
        <td><%= activity.product %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fromuser:</strong>
  <%= @activity.fromUser %>
</p>

<p>
  <strong>Touser:</strong>
  <%= @activity.toUser %>
</p>

<p>
  <strong>Type:</strong>
  <%= @activity.type %>
</p>

<p>
  <strong>Product:</strong>
  <%= @activity.product %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>