config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get    '/login'   => 'devise/sessions#new',     as: :new_session
    post   '/login'   => 'devise/sessions#create',  as: :user_session
    get '/sign_up' => 'users/registrations#new', as: :new_user_session
  end
  resources :test_modules
  resources :activities
  resources :products
  root 'products#index'

  get 'profile' => 'profile#show'
  get 'profile/:id' => 'profile#show', as: 'profile_show'
  post 'profile/follow' => 'profile#follow', as: 'profile_follow'
  post 'profile/unfollow' => 'profile#unfollow', as: 'profile_unfollow'
  get 'profile/:id/followers' => 'profile#followers', as: 'profile_followers'
  get 'profile/:id/following' => 'profile#following', as: 'profile_following'
  get 'profile/:id/shared' => 'profile#sharedProducts', as: 'profile_shared_products'
  get 'list/:id' => 'profile#showList', as: 'profile_list'
  get 'settings' => 'profile#settings', as: 'profile_settings'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "api/:user_email/:user_token/profile/:id" => 'profile#show',
      as: 'api_show_profile', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signin" => "profile#getAuthenticationToken",
      as: 'api_signin', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }
  post "api/signup" => "profile#api_signup",
    as: 'api_signup', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }
 
 get "mrkt/:user_email/:user_token/getMutualFriendsImages/:friends" => 'profile#getMutualFriendsImages',
   as: 'mrkt_get_friends', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPostDetail/:post_id" => 'posts#getPostDetail',
   as: 'mrkt_get_detail', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getYardPosts" => 'posts#getYardPosts',
   as: 'mrkt_get_yardsposts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getPosts" => 'posts#getPosts',
   as: 'mrkt_get_posts', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/createPost" => "posts#createPost",
    as: 'mrkt_create_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ } 

post "mrkt/sendMessage" => "chats#sendMessage",
    as: 'mrkt_send_message', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

 get "mrkt/:user_email/:user_token/getChats" => 'chats#getChats',
   as: 'mrkt_get_chats', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/setLocation" => "profile#setLocation",
    as: 'mrkt_set_location_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ , :latitude =>/[\w+\.-]+/,  :longitude => /[\w+\.-]+/}

 get "mrkt/:user_email/:user_token/setLocation/:latitude/:longitude" => 'profile#setLocation',
   as: 'mrkt_set_location', :defaults => { :format => 'json' }, :constraints => { :user_email => /[^\/]+/ }

post "mrkt/likePost" => "posts#likePost",
    as: 'mrkt_like_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

post "mrkt/dislikePost" => "posts#dislikePost",
    as: 'mrkt_dislike_post', :defaults => { :format => 'json' }, :constraints => { :email => /[^\/]+/ }

  

end

app/models/list.rb
class List < ActiveRecord::Base
	validates :title, presence: true
	has_many :activities
	has_many :products, through: :activities
	has_many :users, through: :activities

end

app/controllers/list_controller.rb
class ListController < ApplicationController

  def displayListForm
  	@list = List.new
    respond_to do |format|
      format.html
      format.js { render 'list_form' }
    end
  end

  def create
  	list = List.new
  	list.title = params[:list][:title]
  	list.user_id = current_user.id
  	list.save
  	activity = Activity.new
  	activity.fromUser = current_user.id
  	activity.activity_type = "list"
  	activity.list_id = list.id
  	activity.save
  	respond_to do |format|
  		format.html
  		format.js { render "create" }
  	end
  end

  def addProductToList
    if params[:list_id].to_i == 0
    else
      if productNotInList(params[:list_id], params[:product_id], current_user.id) == 1 && isUserList(params[:list_id]) == 1
        @success = 1
        activity = Activity.new
        activity.list_id = params[:list_id]
        activity.product_id = params[:product_id]
        activity.fromUser = current_user.id
        activity.activity_type = "add_to_list"
        activity.save
      else
        @success = 0
      end
    end
    respond_to do |format|
      format.html { redirect_to product_path(params[:product_id]) }
      format.js
      format.json
    end
  end

  def productNotInList(list_id, product_id, user_id)
    activity = Activity.where(:list_id => list_id, :product_id => product_id, :fromUser => user_id).first
    if activity.nil?
      return 1
    else
      return 0
    end
  end

  def isUserList(list_id)
    list = List.where(:user_id => current_user.id, :id => list_id).first
    if list.nil?
      return 0
    else
      return 1
    end
  end

end

app/helpers/list_helper.rb
module ListHelper
end

app/views/list/_choose_list.html.erb
        <div class="row">
          <div>
            <div id="list_buttons">
            	<% lists.each do |list| %>
            	<div class="row">
            		<div class="col-md-offset-1 col-md-10">
            		<%= button_to truncate(list.title, :length => 14), {controller: 'list', action: 'addProductToList', :list_id => list.id, :product_id => product_id}, :form => { :id => "vigme-list-form" }, :remote => :true, :method => :post, :class => 'vigme-list-button vigme-rankings-button btn btn-info' %>
            		</div>
                </div>
            	<% end %>
                <div class="row">
                    <div class="col-md-offset-1 col-md-10">
            	<%= button_to "None", {controller: 'list', action: 'addProductToList', :list_id => 0, :product_id => product_id}, :form => { :id => "vigme-list-form" }, :remote => :true, :method => :post, :class => 'vigme-rankings-button btn btn-info' %>
                   </div>
               </div>
            </div>
            </div>
          </div>
        </div>

        <script>


        $(function() {
          return $('form#vigme-list-form').submit(function() {
            $("#close-list-modal").click();
            return console.log("test");
          });
        });
        </script>

app/views/list/_complete.html.erb
<div class="row">
	<div class="col-md-offset-0">
<h3 class="vigme-complete-outfit-header">You've made a new outfit!</h3>
<div class="col-md-offset-1">
<h3 class="vigme-header-3">Save or Add Products to include them in your new outfit!</h3>
</div>
</div>
</div>

app/views/list/_list_form.html.erb
<div id="share_modal_body" class="row">
	<div class="col-md-offset-1">
		<h3 class="vigme-header-3"></h3>
		<%= form_for @list, remote: true, url: list_create_path do |f| %>
			<%= @list.errors.full_messages.first if @list.errors.any? %>

		  <p>
		    <%= f.label :title %><br>
		    <%= f.text_field :title, :class => "vigme-post-product-field" %>
		  </p>
		 
		  <p>
		    <%= f.submit 'Create List', :class => "btn btn-primary" %>
		  </p>
		<% end %>
	</div>
</div>

app/views/list/addProductToList.js.erb
$('#list_modal').modal('hide');

app/views/list/create.js.erb
$('#share_modal_body').replaceWith('<%= escape_javascript(render "complete") %>');

app/views/list/list_form.js.erb
$('#share_modal_body').replaceWith('<%= escape_javascript(render "list_form") %>');